name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          
      - name: Deploy with Helm
        run: |
          helm upgrade --install python-app ./helm/python-app --set image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/python-app --set image.tag=latest
